name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.11"]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install -r requirements-dev.txt
            - name: Download NLP resources
              run: |
                  python -m nltk.downloader punkt stopwords
                  python -m spacy download en_core_web_sm-3.7.0
            - name: Lint
              run: ruff check .
            - name: Tests
              run: python -m pytest -q
            - name: Security (Bandit)
              run: bandit -r . -q || true
